#! /usr/bin/env python

"""Control plot of coast line generated by makecoast.py"""

# ---------
# Imports
# ---------

import matplotlib.pyplot as plt
import numpy as np

# ---------------
# User settings
# ---------------

coastfile = "data/coast.dat"

# -----------
# Read data
# -----------

X, Y = np.loadtxt(coastfile, unpack=True)

# ---------------
# Plot the data
# ---------------

plt.fill(X, Y)
plt.show()
